import * as admin from "firebase-admin";
import { setGlobalOptions } from "firebase-functions/v2";
import { defineString } from "firebase-functions/params";
import { onObjectFinalized } from "firebase-functions/v2/storage";
import * as path from "path";
import * as os from "os";
import * as fs from "fs";
import sharp from "sharp";
import ffmpeg from "fluent-ffmpeg";
import * as ffmpegInstaller from "@ffmpeg-installer/ffmpeg";

admin.initializeApp();
ffmpeg.setFfmpegPath(ffmpegInstaller.path);

// Storage-triggered functions must run in the same region as the bucket.
// Change this to match your default bucket's region (visible in the
// Firebase console under Storage → Files; common values:
// us-east1, us-central1, us-west1, nam5, eur3).
setGlobalOptions({ region: "us-east1", memory: "1GiB", timeoutSeconds: 300 });

// Configured per deploy. The function only processes objects whose path
// starts with STORAGE_PREFIX, and writes thumb/preview URLs to the matching
// Firestore document at `${FIRESTORE_PREFIX}/{nodeId}`.
//
// Set these at deploy time, e.g.:
//   firebase deploy --only functions
// and supply values via `.env` in this directory or via the CLI prompt.
// Example .env:
//   STORAGE_PREFIX=files
//   FIRESTORE_PREFIX=files
//
// Storage object layout the function expects (flat):
//   {STORAGE_PREFIX}/{nodeId}.{ext}       ← original bytes (this triggers)
//   {STORAGE_PREFIX}/thumbs/{nodeId}.jpg  ← generated by this function
//   {STORAGE_PREFIX}/previews/{nodeId}.jpg← generated by this function
//
// Firestore doc layout the function writes to:
//   {FIRESTORE_PREFIX}/{nodeId}
const STORAGE_PREFIX = defineString("STORAGE_PREFIX", {
  description: "Bucket-relative prefix the function should process (e.g. 'files').",
});
const FIRESTORE_PREFIX = defineString("FIRESTORE_PREFIX", {
  description: "Firestore collection path that contains node docs by id (e.g. 'files' or 'users/{uid}/nodes' — must be concrete at deploy time; multi-tenant apps deploy one function per tenant).",
});

const THUMB_WIDTH = 256;
const PREVIEW_WIDTH = 1024;
const THUMB_SUBDIR = "thumbs";
const PREVIEW_SUBDIR = "previews";

/**
 * Triggered on every storage finalize. Processes files that live DIRECTLY
 * under STORAGE_PREFIX (a single path segment); skips objects in the
 * `thumbs/` or `previews/` subfolders (its own outputs) which prevents
 * infinite re-triggering.
 *
 * On success, writes `thumbnailUrl` and `previewUrl` to
 * `${FIRESTORE_PREFIX}/{nodeId}` where nodeId is the object filename
 * with the extension stripped.
 */
export const onUpload = onObjectFinalized(async (event) => {
  const obj = event.data;
  const filePath = obj.name;
  if (!filePath) return;

  const storagePrefix = STORAGE_PREFIX.value();
  const firestorePrefix = FIRESTORE_PREFIX.value();
  if (!storagePrefix || !firestorePrefix) {
    console.warn("STORAGE_PREFIX / FIRESTORE_PREFIX not configured; skipping.");
    return;
  }

  const normalizedPrefix = storagePrefix.replace(/\/+$/, "") + "/";
  if (!filePath.startsWith(normalizedPrefix)) return;

  // Only process files DIRECTLY under the prefix — a remaining path with
  // no additional slashes. Anything with `/` (thumbs/, previews/, other
  // consumer-put subfolders) is skipped. This is what stops the function
  // from processing its own outputs.
  const relative = filePath.substring(normalizedPrefix.length);
  if (relative.includes("/")) return;

  const parsed = path.parse(relative);
  const nodeId = parsed.name; // filename without extension
  if (!nodeId) return;

  const contentType = obj.contentType ?? "";
  const isImage = contentType.startsWith("image/");
  const isVideo = contentType.startsWith("video/");
  if (!isImage && !isVideo) return;

  const bucket = admin.storage().bucket(obj.bucket);
  const tmpOriginal = path.join(os.tmpdir(), `${nodeId}-${parsed.base}`);
  await bucket.file(filePath).download({ destination: tmpOriginal });

  try {
    let thumbBuf: Buffer;
    let previewBuf: Buffer;

    if (isImage) {
      thumbBuf = await sharp(tmpOriginal).rotate().resize({ width: THUMB_WIDTH }).jpeg({ quality: 75 }).toBuffer();
      previewBuf = await sharp(tmpOriginal).rotate().resize({ width: PREVIEW_WIDTH }).jpeg({ quality: 80 }).toBuffer();
    } else {
      const tmpFrame = path.join(os.tmpdir(), `${nodeId}-frame.jpg`);
      await extractVideoFrame(tmpOriginal, tmpFrame);
      thumbBuf = await sharp(tmpFrame).resize({ width: THUMB_WIDTH }).jpeg({ quality: 75 }).toBuffer();
      previewBuf = await sharp(tmpFrame).resize({ width: PREVIEW_WIDTH }).jpeg({ quality: 80 }).toBuffer();
      fs.unlinkSync(tmpFrame);
    }

    const prefixTrimmed = storagePrefix.replace(/\/+$/, "");
    const thumbPath = `${prefixTrimmed}/${THUMB_SUBDIR}/${nodeId}.jpg`;
    const previewPath = `${prefixTrimmed}/${PREVIEW_SUBDIR}/${nodeId}.jpg`;

    await Promise.all([
      bucket.file(thumbPath).save(thumbBuf, { contentType: "image/jpeg", resumable: false }),
      bucket.file(previewPath).save(previewBuf, { contentType: "image/jpeg", resumable: false }),
    ]);

    const [thumbUrl, previewUrl] = await Promise.all([
      signedUrl(bucket, thumbPath),
      signedUrl(bucket, previewPath),
    ]);

    const docPath = `${firestorePrefix.replace(/\/+$/, "")}/${nodeId}`;
    await admin.firestore().doc(docPath).update({
      thumbnailUrl: thumbUrl,
      previewUrl: previewUrl,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
  } finally {
    if (fs.existsSync(tmpOriginal)) fs.unlinkSync(tmpOriginal);
  }
});

function extractVideoFrame(input: string, output: string): Promise<void> {
  return new Promise((resolve, reject) => {
    ffmpeg(input)
      .on("end", () => resolve())
      .on("error", reject)
      .screenshots({ timestamps: ["1"], filename: path.basename(output), folder: path.dirname(output) });
  });
}

async function signedUrl(bucket: ReturnType<typeof admin.storage>["bucket"] extends () => infer R ? R : never, p: string): Promise<string> {
  // Long-lived signed URL — adjust for your needs (or use getDownloadURL via client).
  const [url] = await bucket.file(p).getSignedUrl({
    action: "read",
    expires: Date.now() + 1000 * 60 * 60 * 24 * 365 * 10, // 10y
  });
  return url;
}
