/// Firestore document schema used by the Firebase implementation.
///
/// The collection path is supplied by the caller (see
/// `FirebaseCloudStorage(firestorePath: ...)`). Within whatever collection
/// the caller chooses, each document has this shape:
///
/// ```
/// {firestorePath}/{nodeId}
///     type:         "file" | "folder"
///     name:         string
///     parentId:     string  // "" for the root within the caller's namespace
///     path:         string  // "/photos/2025"
///     mimeType:     string?     // files only
///     sizeBytes:    int?        // files only
///     storagePath:  string?     // files only — absolute bucket path
///     downloadUrl:  string?     // files only
///     thumbnailUrl: string?     // populated by the Cloud Function
///     previewUrl:   string?     // populated by the Cloud Function
///     createdAt:    Timestamp
///     updatedAt:    Timestamp
/// ```
///
/// Storage bucket layout is flat:
///
/// ```
/// {storageRoot}/{nodeId}.{ext}       ← original bytes
/// {storageRoot}/thumbs/{nodeId}.jpg  ← generated by Cloud Function
/// {storageRoot}/previews/{nodeId}.jpg← generated by Cloud Function
/// ```
///
/// The Firestore folder hierarchy is entirely independent — moving/renaming
/// a file in Firestore never touches the Storage bytes.
library firestore_schema;

const String kFieldType = 'type';
const String kFieldName = 'name';
const String kFieldParentId = 'parentId';
const String kFieldPath = 'path';
const String kFieldMimeType = 'mimeType';
const String kFieldSizeBytes = 'sizeBytes';
const String kFieldStoragePath = 'storagePath';
const String kFieldDownloadUrl = 'downloadUrl';
const String kFieldThumbnailUrl = 'thumbnailUrl';
const String kFieldPreviewUrl = 'previewUrl';
const String kFieldCreatedAt = 'createdAt';
const String kFieldUpdatedAt = 'updatedAt';

const String kTypeFile = 'file';
const String kTypeFolder = 'folder';

/// Storage path for the original bytes: `{storageRoot}/{nodeId}{.ext}`.
///
/// Flat layout — files live directly under [storageRoot] and are keyed by
/// nodeId (collision-free). Thumbnails and previews go in sibling
/// `thumbs/` and `previews/` subfolders (see [thumbPathFor],
/// [previewPathFor]).
String storagePathFor(String storageRoot, String nodeId, String extension) {
  final ext = extension.isEmpty
      ? ''
      : (extension.startsWith('.') ? extension : '.$extension');
  return '${_trimTrailingSlash(storageRoot)}/$nodeId$ext';
}

/// Storage path for the thumbnail JPEG produced by the Cloud Function.
String thumbPathFor(String storageRoot, String nodeId) =>
    '${_trimTrailingSlash(storageRoot)}/thumbs/$nodeId.jpg';

/// Storage path for the preview JPEG produced by the Cloud Function.
String previewPathFor(String storageRoot, String nodeId) =>
    '${_trimTrailingSlash(storageRoot)}/previews/$nodeId.jpg';

String _trimTrailingSlash(String path) =>
    path.endsWith('/') ? path.substring(0, path.length - 1) : path;
